version: "3.9"

services:
  web:
    build:
      context: .                     # корінь репо (щоб спрацював COPY docker/local/entrypoint.sh ...)
      dockerfile: docker/local/Dockerfile
    env_file:
      - .env                         # зроби з docker/.env.example: cp docker/.env.example .env
    ports:
      - "8000:8000"                  # http://localhost:8000
    volumes:
      - .:/app                       # hot-reload коду
      - media:/app/media             # зберігання завантажень
    restart: unless-stopped

volumes:
  media: